"""init_db

Revision ID: 4dc09c0b6d9a
Revises: b0e9d8fe40e4
Create Date: 2024-07-12 16:36:41.290262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc09c0b6d9a'
down_revision: Union[str, None] = 'b0e9d8fe40e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
                    sa.Column('pk_id', sa.Integer(), nullable=False),
                    sa.Column('nome', sa.String(length=50), nullable=False),
                    sa.Column('id', sa.UUID(),nullable=False),
                    sa.PrimaryKeyConstraint('pk_id'),
                    sa.Uniqueconstraint('nome')
                    )
    op.create_table('centro_treinamento',
                    sa.Column('pk_id', sa.Integer(), nullable=False),
                    sa.Column('nome', sa.String(length=50), nullable=False),
                    sa.Column('proprietario', sa.String(length=50), nullable=False),
                    sa.Column('endereco', sa.String(length=50), nullable=False),
                    sa.Column('id', sa.UUID(),nullable=False),
                    sa.PrimaryKeyConstraint('pk_id'),
                    sa.Uniqueconstraint('nome')
                    )
    op.create_table('atletas',
                    sa.Column('pk_id', sa.Integer(), nullable=False),
                    sa.Column('nome', sa.String(length=50), nullable=False),
                    sa.Column('cpf', sa.String(length=11), nullable=False),
                    sa.Column('idade', sa.String(length=50), nullable=False),
                    sa.Column('peso', sa.String(length=50), nullable=False),
                    sa.Column('altura', sa.String(length=50), nullable=False),
                    sa.Column('sexo', sa.String(length=1), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('centro_treinamento_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.UUID(),nullable=False),
                    sa.PrimaryKeyConstraint('pk_id'),
                    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.pk_id']),
                    sa.ForeingKeyConstraint(['centro_treinamento_id'], ['centro_treinamento.pk_id']),
                    sa.Uniqueconstraint('cpf'))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atletas')
    op.drop_table('centro_treinamento')
    op.drop_table('categorias')
    pass
    # ### end Alembic commands ###
